### ISSUE TITLE
with visiting your data updated impressed me about the question how does the 3d printer component design which support the structure

### ISSUE THREAD

**Issue by 714902777** [PtD/frankenstein-cnc#1]
is it still in construction

**Comment by 714902777** [comment]
--------------------Configuration: Mach3MQTT - Win32 Debug--------------------
Compiling...
Mach3MQTT.cpp
c:\program files\microsoft visual studio\vc98\mfc\include\afxv_w32.h(119) : warning C4005: '_WIN32_WINDOWS' : macro redefinition
        f:\frankenstein-cnc-master\software\mach3\mach3mqttplugin\stdafx.h(23) : see previous definition of '_WIN32_WINDOWS'
NOTE: WINVER has been defined as 0x0500 or greater which enables
Windows NT 5.0 and Windows 98 features. When these headers were released,
Windows NT 5.0 beta 1 and Windows 98 beta 2.1 were the current versions.
For this release when WINVER is defined as 0x0500 or greater, you can only
build beta or test applications.  To build a retail application,
set WINVER to 0x0400 or visit http://www.microsoft.com/msdn/sdk
to see if retail Windows NT 5.0 or Windows 98 headers are available.
See the SDK release notes for more information.
f:\frankenstein-cnc-master\software\mach3\mach3mqttplugin\mach3mqtt.h(7) : fatal error C1083: Cannot open include file: '_TrajectoryControl.h': No such file or directory
执行 cl.exe 时出错.

Mach3MQTT.obj - 1 error(s), 0 warning(s)

**Comment by PtD** [comment]
It's rather functional. However, in order to compile it, you need to obtain Mach3 SDK. It's described here: https://github.com/PtD/frankenstein-cnc/tree/master/Software/Mach3/Mach3MQTTPlugin
